## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os
import glob
import shutil
import pdb

## Load Input

In [75]:
val_dir = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Train_val_LB/val/"
val_dirs = glob.glob(os.path.join(val_dir, "*.svs"))
ground_truth_dataset=pd.DataFrame()
for v in val_dirs:
    l = glob.glob(os.path.join(v, "images", "*"))
    if len(ground_truth_dataset)==0:
        ground_truth_dataset = pd.DataFrame({"image_path":l})
    else:
        ground_truth_dataset = pd.concat([ground_truth_dataset, pd.DataFrame({"image_path":l})],ignore_index=True)

In [76]:
ground_truth_dataset["image_name"]=ground_truth_dataset["image_path"].apply(lambda l:l.split("/")[-1])
ground_truth_dataset["image_name"] =  ground_truth_dataset["image_name"].apply(lambda l: l.replace(".png",""))
ground_truth_dataset["image_name"] =  ground_truth_dataset["image_name"].apply(lambda l: l.replace(".svs",""))

In [77]:
ground_truth_dataset["wsi_id"]=ground_truth_dataset["image_path"].apply(lambda l:l.split("/")[-1].split("_CG_")[0])

In [78]:
len(ground_truth_dataset["wsi_id"].unique())

17

In [79]:
ground_truth_dataset["ground_truth"]=True

In [80]:
ground_truth_dataset

,image_path,image_name,wsi_id,ground_truth
0,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1_CG_36864x_16384y_image,PD306_Syn1,True
1,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1_CG_36864x_26624y_image,PD306_Syn1,True
2,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1_CG_23552x_21504y_image,PD306_Syn1,True
3,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1_CG_25600x_13312y_image,PD306_Syn1,True
4,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1_CG_34816x_14336y_image,PD306_Syn1,True
...,...,...,...,...
510,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1_CG_200x_43008x_6144y_image,01_156_Syn1,True
511,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1_CG_200x_22528x_6144y_image,01_156_Syn1,True
512,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1_CG_200x_28672x_21504y_image,01_156_Syn1,True
513,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1_CG_200x_20480x_11264y_image,01_156_Syn1,True
514,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1_CG_200x_23552x_14336y_image,01_156_Syn1,True

In [81]:
ground_truth_dataset.to_csv("/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/image_level_ground_truths.csv")

## Load Output

In [18]:
result_data_path = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/super-disco-93/"
result_data_path = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/"
result_folders = glob.glob(os.path.join(result_data_path, "*.svs"))
print(result_folders)
#destination_path = "/home/vivek/Projects/amyb-plaque-detection/reports/"
#csv_dir = os.path.join(os.path.dirname(destination_path), "csv_data")
#if not os.path.exists(csv_dir):
#    os.makedirs(csv_dir)
final_csv_merged = pd.DataFrame()
for result_folder in result_folders:
    csv_file = glob.glob(os.path.join(result_folder, "*.csv"))
    print(csv_file)
    print(len(csv_file))
    if (len(csv_file) == 0) or (os.path.getsize(csv_file[0])<2):
        print("Empty", result_folder)
        continue
    
    if len(csv_file)>1:
        print(">1 csv files")
        break
    
    if len(csv_file)==1:
        csv_file = pd.read_csv(csv_file[0])
        print(len(csv_file))
        
    
    
    if (len(final_csv_merged)==0):
        final_csv_merged=csv_file
    else:
        final_csv_merged=pd.concat([final_csv_merged,csv_file])

['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD306_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD013_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD334_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD295_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/11_063_CG_aSyn_x200.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/02_021_Syn1_CG_200x.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD311_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/01_104_Syn1_CG_200x.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD309_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/00_1027_Syn1_CG_200x.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/14_153_CG_aSyn_x200.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/02_019_Syn1_CG_200x.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD130_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/13_131_CG_aSyn_x200.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD336_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD041_Syn1_CG.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/00_1108_Syn1_CG_200x.svs', '/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/01_156_Syn1_CG_200x.svs']
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD306_Syn1_CG.svs/PD306_Syn1_CG.svs_quantify.csv']
1
239
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD013_Syn1_CG.svs/PD013_Syn1_CG.svs_quantify.csv']
1
Empty /gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD013_Syn1_CG.svs
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD334_Syn1_CG.svs/PD334_Syn1_CG.svs_quantify.csv']
1
51
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD295_Syn1_CG.svs/PD295_Syn1_CG.svs_quantify.csv']
1
21
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/11_063_CG_aSyn_x200.svs/11_063_CG_aSyn_x200.svs_quantify.csv']
1
2
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/02_021_Syn1_CG_200x.svs/02_021_Syn1_CG_200x.svs_quantify.csv']
1
198
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD311_Syn1_CG.svs/PD311_Syn1_CG.svs_quantify.csv']
1
70
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/01_104_Syn1_CG_200x.svs/01_104_Syn1_CG_200x.svs_quantify.csv']
1
15
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD309_Syn1_CG.svs/PD309_Syn1_CG.svs_quantify.csv']
1
174
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/00_1027_Syn1_CG_200x.svs/00_1027_Syn1_CG_200x.svs_quantify.csv']
1
10
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/14_153_CG_aSyn_x200.svs/14_153_CG_aSyn_x200.svs_quantify.csv']
1
138
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/02_019_Syn1_CG_200x.svs/02_019_Syn1_CG_200x.svs_quantify.csv']
1
2
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD130_Syn1_CG.svs/PD130_Syn1_CG.svs_quantify.csv']
1
5
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/13_131_CG_aSyn_x200.svs/13_131_CG_aSyn_x200.svs_quantify.csv']
1
2
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD336_Syn1_CG.svs/PD336_Syn1_CG.svs_quantify.csv']
1
68
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/PD041_Syn1_CG.svs/PD041_Syn1_CG.svs_quantify.csv']
1
11
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/00_1108_Syn1_CG_200x.svs/00_1108_Syn1_CG_200x.svs_quantify.csv']
1
14
['/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/Reports/figures/royal-butterfly-145_mrcnn_model_10/01_156_Syn1_CG_200x.svs/01_156_Syn1_CG_200x.svs_quantify.csv']
1
57

In [55]:
final_csv_merged

,image_name,label,confidence,brown_pixels,True,Pre,False,centroid,eccentricity,area,equivalent_diameter
0,PD306_Syn1_CG_36864x_16384y_image,True,0.918591,0,1,0,0,"(15.54077791718946, 13.053952321204516)",0.406021,797,31.855485
1,PD306_Syn1_CG_36864x_16384y_image,True,0.917707,0,1,0,0,"(10.771543086172345, 10.879759519038076)",0.324409,499,25.206081
2,PD306_Syn1_CG_36864x_16384y_image,True,0.800760,0,1,0,0,"(12.474327628361857, 9.88997555012225)",0.569447,409,22.820056
3,PD306_Syn1_CG_36864x_26624y_image,True,0.932231,0,1,0,0,"(14.010233918128655, 15.425438596491228)",0.593685,684,29.510945
4,PD306_Syn1_CG_36864x_26624y_image,True,0.870971,0,1,0,0,"(9.676025917926566, 14.503239740820735)",0.780761,463,24.279825
...,...,...,...,...,...,...,...,...,...,...,...
52,01_156_Syn1_CG_200x_22528x_6144y_image,True,0.851498,0,1,0,0,"(15.044016506189822, 14.385144429160935)",0.587085,727,30.424417
53,01_156_Syn1_CG_200x_28672x_21504y_image,True,0.897444,0,1,0,0,"(16.272933182332956, 14.733861834654586)",0.481584,883,33.530143
54,01_156_Syn1_CG_200x_23552x_14336y_image,True,0.859945,0,1,0,0,"(11.449523809523809, 11.998095238095239)",0.446634,525,25.854415
55,01_156_Syn1_CG_200x_23552x_14336y_image,True,0.857138,0,1,0,0,"(11.790082644628098, 15.418181818181818)",0.533867,605,27.754458
56,01_156_Syn1_CG_200x_23552x_14336y_image,True,0.819259,0,1,0,0,"(12.333333333333334, 13.865921787709498)",0.488377,537,26.148224

In [56]:
final_csv_merged["image_name"].values

array(['PD306_Syn1_CG_36864x_16384y_image',
       'PD306_Syn1_CG_36864x_16384y_image',
       'PD306_Syn1_CG_36864x_16384y_image', ...,
       '01_156_Syn1_CG_200x_23552x_14336y_image',
       '01_156_Syn1_CG_200x_23552x_14336y_image',
       '01_156_Syn1_CG_200x_23552x_14336y_image'], dtype=object)

## Merge Predicted & Ground Truth

In [ ]:
predicted_labels=final_csv_merged

In [42]:
predicted_labels_merged = pd.merge(predicted_labels,ground_truth_dataset,on="image_name", how="left")

In [43]:
predicted_labels_merged

,image_name,label,confidence,brown_pixels,True,Pre,False,centroid,eccentricity,area,equivalent_diameter,image_path,wsi_id,ground_truth
0,PD306_Syn1_CG_36864x_16384y_image,True,0.918591,0,1,0,0,"(15.54077791718946, 13.053952321204516)",0.406021,797,31.855485,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1,True
1,PD306_Syn1_CG_36864x_16384y_image,True,0.917707,0,1,0,0,"(10.771543086172345, 10.879759519038076)",0.324409,499,25.206081,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1,True
2,PD306_Syn1_CG_36864x_16384y_image,True,0.800760,0,1,0,0,"(12.474327628361857, 9.88997555012225)",0.569447,409,22.820056,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1,True
3,PD306_Syn1_CG_36864x_26624y_image,True,0.932231,0,1,0,0,"(14.010233918128655, 15.425438596491228)",0.593685,684,29.510945,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1,True
4,PD306_Syn1_CG_36864x_26624y_image,True,0.870971,0,1,0,0,"(9.676025917926566, 14.503239740820735)",0.780761,463,24.279825,/gladstone/finkbeiner/steve/work/data/npsad_da...,PD306_Syn1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1072,01_156_Syn1_CG_200x_22528x_6144y_image,True,0.851498,0,1,0,0,"(15.044016506189822, 14.385144429160935)",0.587085,727,30.424417,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1,True
1073,01_156_Syn1_CG_200x_28672x_21504y_image,True,0.897444,0,1,0,0,"(16.272933182332956, 14.733861834654586)",0.481584,883,33.530143,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1,True
1074,01_156_Syn1_CG_200x_23552x_14336y_image,True,0.859945,0,1,0,0,"(11.449523809523809, 11.998095238095239)",0.446634,525,25.854415,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1,True
1075,01_156_Syn1_CG_200x_23552x_14336y_image,True,0.857138,0,1,0,0,"(11.790082644628098, 15.418181818181818)",0.533867,605,27.754458,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1,True
1076,01_156_Syn1_CG_200x_23552x_14336y_image,True,0.819259,0,1,0,0,"(12.333333333333334, 13.865921787709498)",0.488377,537,26.148224,/gladstone/finkbeiner/steve/work/data/npsad_da...,01_156_Syn1,True

In [44]:
predicted_labels_merged["matched"]=np.where(predicted_labels_merged["label"]==predicted_labels_merged["ground_truth"],1,0)

In [45]:
predicted_labels_merged["matched"].sum()/len(predicted_labels_merged)

1.0

In [64]:
predicted_labels_merged["wsi_id"]=predicted_labels_merged["image_name"].apply(lambda l:l.split("_CG_")[0])

In [65]:
predicted_labels_merged["wsi_id"].unique()

array(['PD306_Syn1', 'PD334_Syn1', 'PD295_Syn1', '11_063', '02_021_Syn1',
       'PD311_Syn1', '01_104_Syn1', 'PD309_Syn1', '00_1027_Syn1',
       '14_153', '02_019_Syn1', 'PD130_Syn1', '13_131', 'PD336_Syn1',
       'PD041_SYN1', '00_1108_Syn1', '01_156_Syn1'], dtype=object)

In [46]:
wsi_ids = predicted_labels_merged["wsi_id"].unique()
for p in wsi_ids:
    t = predicted_labels_merged[predicted_labels_merged["wsi_id"]==p]
    print(p, t["matched"].sum()/len(t))

PD306_Syn1 1.0
PD334_Syn1 1.0
PD295_Syn1 1.0
11_063 1.0
02_021_Syn1 1.0
PD311_Syn1 1.0
01_104_Syn1 1.0
PD309_Syn1 1.0
00_1027_Syn1 1.0
14_153 1.0
02_019_Syn1 1.0
PD130_Syn1 1.0
13_131 1.0
PD336_Syn1 1.0
PD041_SYN1 1.0
00_1108_Syn1 1.0
01_156_Syn1 1.0

In [47]:
ground_truth_dataset = pd.merge(ground_truth_dataset, predicted_labels, how="left", on = ["image_name"])

In [50]:
1- (ground_truth_dataset["label"].isna().sum()/len(ground_truth_dataset))

0.9134860050890585

## LBD Type Analysis

In [59]:
ground_truth_dataset["LBD_type"] = np.where(ground_truth_dataset["image_name"].str.startswith("PD"),"PDD","DLB")

In [62]:
ground_truth_dataset["LBD_type"].value_counts()/len(ground_truth_dataset)

PDD    0.586938
DLB    0.413062
Name: LBD_type, dtype: float64

In [64]:
ground_truth_dataset[~ground_truth_dataset["label"].isna()]["LBD_type"].value_counts()/len(ground_truth_dataset[~ground_truth_dataset["label"].isna()])

PDD    0.593315
DLB    0.406685
Name: LBD_type, dtype: float64

In [69]:
ground_truth_dataset.groupby(["LBD_type"])["wsi_id"].nunique()

LBD_type
DLB    9
PDD    8
Name: wsi_id, dtype: int64

In [70]:
ground_truth_dataset.groupby(["LBD_type","wsi_id"])["image_name"].count()

LBD_type  wsi_id
DLB       00_1027_Syn1     15
          00_1108_Syn1     27
          01_104_Syn1      23
          01_156_Syn1      61
          02_019_Syn1       5
          02_021_Syn1     207
          11_063            5
          13_131            3
          14_153          141
PDD       PD041_SYN1       21
          PD130_Syn1       15
          PD295_Syn1       36
          PD306_Syn1      247
          PD309_Syn1      177
          PD311_Syn1       73
          PD334_Syn1       52
          PD336_Syn1       71
Name: image_name, dtype: int64

In [71]:
ground_truth_dataset.groupby(["LBD_type"])["area"].describe()

          count        mean         std    min     25%    50%    75%     max
LBD_type
DLB       438.0  604.269406  221.867022  210.0  433.25  573.0  760.0  1736.0
PDD       639.0  539.043818  193.555338  169.0  396.00  506.0  662.5  1298.0

In [72]:
ground_truth_dataset.groupby(["LBD_type"])["equivalent_diameter"].describe()

,count,mean,std,min,25%,50%,75%,max
LBD_type,,,,,,,,
DLB,438.0,27.277894,5.035282,16.351768,23.486754,27.010443,31.107267,47.014294
PDD,639.0,25.784825,4.637709,14.668929,22.454462,25.382262,29.043434,40.652982