# Import Libraries

In [12]:
import sys
#TODO change hardcoding
sys.path.append('../../../')
from concurrent.futures import process
import os
import glob
from posixpath import dirname
import re
from turtle import pd
from cv2 import THRESH_BINARY_INV, THRESH_OTSU
import numpy as np
from requests import delete
import cv2
import pyvips as Vips
from tqdm import tqdm
import pyfiglet
import argparse
import pdb
import skimage.io as io
#from src.utils import vips_utils, normalize
import matplotlib.pyplot as plt
from skimage.io import imread, imsave
import time
from timeit import default_timer as timer
from threading import Thread
from concurrent.futures import ThreadPoolExecutor, wait, ALL_COMPLETED
import subprocess
import geojson
import os
from PIL import Image
import pyvips as Vips
from Reinhard import Reinhard
import pandas as pd

## Load Data

In [13]:
dlb_wsi_dir = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD_Dataset/LBD/DLB_cases"
pdd_wsi_dir = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD_Dataset/LBD/PDD_cases/PDD_cases"
wsi_home_dir = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD_Dataset/LBD/"

In [14]:
json_dir = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/GeoJsons_Red_Mark_included"

In [15]:
f_list = os.listdir(json_dir)
#f_list.remove('.DS_Store')

In [16]:
f_list

['PD130_Syn1_CG.svs.geojson',
 'PD131_Syn1_CG.svs.geojson',
 'PD090_Syn1_CG.svs.geojson',
 'PD079_Syn1_CG.svs.geojson',
 'PD088_Syn1_CG.svs.geojson',
 'PD110_Syn1_CG.svs.geojson',
 'PD001_Syn1_CG.svs.geojson',
 'PD113_Syn1_CG.svs.geojson',
 'PD067_Syn1_CG.svs.geojson',
 'PD133_Syn1_CG.svs.geojson',
 'PD061_Syn1_CG.svs.geojson',
 'PD013_Syn1_CG.svs.geojson']

In [17]:
#filename_correction
import os
f_list_updated_names = []
for file in f_list:
    x = file.replace("SYN1", "Syn1")
    os.rename(os.path.join(json_dir,file),os.path.join(json_dir, x))
    f_list_updated_names.append(x)

In [18]:
f_list_updated_names

['PD130_Syn1_CG.svs.geojson',
 'PD131_Syn1_CG.svs.geojson',
 'PD090_Syn1_CG.svs.geojson',
 'PD079_Syn1_CG.svs.geojson',
 'PD088_Syn1_CG.svs.geojson',
 'PD110_Syn1_CG.svs.geojson',
 'PD001_Syn1_CG.svs.geojson',
 'PD113_Syn1_CG.svs.geojson',
 'PD067_Syn1_CG.svs.geojson',
 'PD133_Syn1_CG.svs.geojson',
 'PD061_Syn1_CG.svs.geojson',
 'PD013_Syn1_CG.svs.geojson']

In [9]:
count_dlb,count_pdd = 0,0
for file in f_list:
    if file.startswith("PD"):
        count_pdd = count_pdd+1
    else:
        count_dlb=count_dlb+1
print("PDD cases: ", count_pdd)
print("DLB cases: ", count_dlb)

PDD cases:  16
DLB cases:  16

In [10]:
#imagenames = sorted(glob.glob(os.path.join(wsi_home_dir, './*/*.svs')))
dlb_imagenames = sorted(glob.glob(os.path.join(dlb_wsi_dir, './*.svs')))
pdd_imagenames = sorted(glob.glob(os.path.join(pdd_wsi_dir, '././*.svs')))

In [11]:
pdd_imagenames[0]

'/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD_Dataset/LBD/PDD_cases/PDD_cases/././PD001_Syn1_CG.svs'

## Utility Functions

In [19]:
tilesize = 1024
workers = 10
#save_dir = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/WM_images" ## This excluded red marked annotation
save_dir = "/gladstone/finkbeiner/steve/work/data/npsad_data/monika/LBD/WM_images_RedMarked" ## This includes red marked annotation
stride = 256
REF_IMG_PATH = dlb_imagenames[0]
color_codes =  {"White":(0,154,205), "grey":(255, 170, 51),"bg":(128,0,128)}

def normalization(REF_IMG_PATH):
    print("Init Normalization")
    ref_image = Vips.Image.new_from_file(REF_IMG_PATH)
    normalizer = Reinhard()
    normalizer.fit(ref_image)
    return normalizer

def getVipsInfo(vips_img):
    # # Get bounds-x and bounds-y offeset
    vfields = [f.split('.') for f in vips_img.get_fields()]
    vfields = [f for f in vfields if f[0] == 'openslide']
    vfields = dict([('.'.join(k[1:]), vips_img.get('.'.join(k))) for k in vfields])
    return vfields

def get_points_in_contour(x,y,downscaled_w,downscaled_h,cnt,stride, tilesize):
    points = []
    stride = stride
    for x_val in range(x, x+downscaled_w-stride, stride): 
        for y_val in range(y, y + downscaled_h-stride, stride): 
            inside_1 = cv2.pointPolygonTest(cnt, (x_val, y_val), False)
            inside_2 = cv2.pointPolygonTest(cnt, (x_val+tilesize, y_val+tilesize), False)
            inside_3 = cv2.pointPolygonTest(cnt, (x_val, y_val+tilesize), False)
            inside_4 = cv2.pointPolygonTest(cnt, (x_val+tilesize, y_val), False)
            if (inside_1>= 0) and (inside_2>=0) and (inside_3>=0) and (inside_4>=0) : 
                points.append((x_val, y_val)) # points time scale factor print(f'Collected {len(self.points)} points') return self.points 
    return points

def crop_process(i, x, y, vips_orig_img, savesubdir, orig_w, orig_h):   
    print("Crop slide thread Started.", i) 
    savecroppath = os.path.join(savesubdir, f'{filename}_x_{x}_y_{y}.png')
    # row is y, col is x
    if y + tilesize < orig_h and x + tilesize < orig_w:
        # TODO change to vips cropping
        print("---------copying image---------")
        crop = vips_orig_img.crop(x, y, 1024, 1024)
        crop.write_to_file(savecroppath)
        print("Thread Stopped ", i)
        return 1
    else:
        print("Thread Stopped ", i)
        return 0


def tiling(cnt,vips_img, vips_array_copy, filename, class_type, orig_w, orig_h):
    cnt = cnt.astype(np.int)
    x,y,downscaled_w,downscaled_h = cv2.boundingRect(cnt)
    vips_array_copy = cv2.drawContours(vips_array_copy, [cnt],-1, (0,0,255),40)
    vips_array_copy = cv2.rectangle(vips_array_copy,(x, y),(x + downscaled_w,y + downscaled_h),(0,255,0),30)
    points = get_points_in_contour(x,y,downscaled_w,downscaled_h,cnt,stride, tilesize)
    for x, y in points:
        vips_array_copy = cv2.rectangle(vips_array_copy,(x, y),(x + tilesize,y + tilesize),color_codes[class_type],30)
    th = Image.fromarray(vips_array_copy)
    th.thumbnail((1000,1000))

    save_path = os.path.join(save_dir, filename)
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    th.save(os.path.join(save_path,filename.split(".")[0]+".png"))
    
    savesubdir = os.path.join(save_path, class_type)
    if not os.path.exists(savesubdir):
        os.makedirs(savesubdir)

    exe = ThreadPoolExecutor(max_workers=workers)
    futures = [exe.submit(crop_process, i, x_1, y_1, vips_img, savesubdir, orig_w, orig_h) for i, (x_1, y_1) in enumerate(points)]

    done, not_done = wait(futures, return_when=ALL_COMPLETED)
    exe.shutdown()
    print("done tiling")
    #return futures

In [20]:
normalizer = normalization(REF_IMG_PATH)

Init Normalization

In [21]:

annotations_df = pd.DataFrame({"filename": f_list_updated_names,"filepath":[os.path.join(json_dir,x) for x in f_list_updated_names]})

In [22]:
annotations_df

,filename,filepath
0,PD130_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
1,PD131_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
2,PD090_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
3,PD079_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
4,PD088_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
5,PD110_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
6,PD001_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
7,PD113_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
8,PD067_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
9,PD133_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
10,PD061_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...
11,PD013_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...

In [28]:
def count_annotations_flag(filename, label):
    path = save_dir
    annotated_images = os.listdir(path)
    #annotated_images.remove('.DS_Store')
    filename = filename.replace(".geojson","")
    if filename in annotated_images:
        if os.path.exists(os.path.join(path,filename, label)):
            items = os.listdir(os.path.join(path,filename, label))
            #items = [len(os.listdir(os.path.join(path,filename,i))) for i in wgm_dir]
            return len(items)
        else:
            print("folder does not exist")
            return 0
    else:
        return None

In [29]:
annotations_df["WM_count"]=annotations_df["filename"].apply(lambda l:count_annotations_flag(l,"White"))
annotations_df["GM_count"]=annotations_df["filename"].apply(lambda l:count_annotations_flag(l,"grey"))
annotations_df["bg_count"]=annotations_df["filename"].apply(lambda l:count_annotations_flag(l,"bg"))

In [30]:
annotations_df

,filename,filepath,WM_count,GM_count,bg_count
0,PD130_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
1,PD131_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
2,PD090_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
3,PD079_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
4,PD088_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
5,PD110_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
6,PD001_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
7,PD113_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
8,PD067_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
9,PD133_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
10,PD061_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
11,PD013_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None

In [26]:
annotations_df["wm_gm_ratio"] = annotations_df["WM_count"]/annotations_df["GM_count"]

In [27]:
annotations_df

,filename,filepath,WM_count,GM_count,bg_count,wm_gm_ratio
0,14_148_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2253,3399,4110,0.662842
1,PD130_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,321,677,1268,0.474151
2,15_007_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,1254,104,1944,12.057692
3,PD131_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,204,678,1364,0.300885
4,PD090_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,960,1879,1018,0.510910
5,13_131_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2439,5416,1008,0.450332
6,12_007_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2204,901,2891,2.446171
7,14_053_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2189,3402,2293,0.643445
8,PD079_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,836,1326,1020,0.630468
9,13_177_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,3059,787,2422,3.886912
10,PD088_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2794,3370,2144,0.829080
11,15_005_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,1959,3493,4095,0.560836
12,PD110_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,292,1976,841,0.147773
13,14_087_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,782,55,879,14.218182
14,PD001_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,234,73,260,3.205479
15,PD034_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2417,2348,976,1.029387
16,PD113_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,1525,1158,2001,1.316926
17,14_133_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,5582,2459,4092,2.270028
18,14_036_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,3903,3965,1364,0.984363
19,14_073_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2962,6405,1320,0.462451
20,PD002_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,2553,2505,5512,1.019162
21,11_063_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,3678,2415,1056,1.522981
22,PD067_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,738,869,1017,0.849252
23,14_153_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,4159,2776,2574,1.498199
24,PD041_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,1205,572,672,2.106643
25,PD133_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,322,797,844,0.404015
26,12_060_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,5144,1708,2256,3.011710
27,14_075_CG_aSyn_x200.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,1920,4741,3084,0.404978
28,PD017_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,1382,2897,20,0.477045
29,PD061_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,1024,775,3406,1.321290
30,PD013_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,507,318,736,1.594340

In [29]:
annotations_df.to_csv("/home/mahirwar/Desktop/Monika/npsad_data/monika/LBD/WM_Annotations.csv")

In [31]:
geofiles_to_annotate =  annotations_df[annotations_df["WM_count"].isna()]["filename"].values
print(geofiles_to_annotate)

['PD130_Syn1_CG.svs.geojson' 'PD131_Syn1_CG.svs.geojson'
 'PD090_Syn1_CG.svs.geojson' 'PD079_Syn1_CG.svs.geojson'
 'PD088_Syn1_CG.svs.geojson' 'PD110_Syn1_CG.svs.geojson'
 'PD001_Syn1_CG.svs.geojson' 'PD113_Syn1_CG.svs.geojson'
 'PD067_Syn1_CG.svs.geojson' 'PD133_Syn1_CG.svs.geojson'
 'PD061_Syn1_CG.svs.geojson' 'PD013_Syn1_CG.svs.geojson']

In [32]:
geofiles_to_annotate =  annotations_df[annotations_df["WM_count"].isna()]["filename"].values
for geofile in geofiles_to_annotate:
    with open(os.path.join(json_dir,geofile)) as f:
        gj = geojson.load(f)
    filename = geofile.replace(".geojson","")
    features = gj['features']
    print(filename)
    if filename.startswith("PD"):
        img = os.path.join(pdd_wsi_dir, filename)
    else:
        img = os.path.join(dlb_wsi_dir, filename)
    #  print(geo_name, len(features))
    vips_img = Vips.Image.new_from_file(img, level=0)
    vips_img = normalizer.transform(vips_img)
    vinfo = getVipsInfo(vips_img)
    orig_w, orig_h = int(vinfo['level[0].width']), int(vinfo['level[0].height'])
    vips_array = np.ndarray(buffer=vips_img.write_to_memory(), dtype=np.uint8, shape=(vips_img.height, vips_img.width, vips_img.bands))
    vips_array = vips_array[:,:,:3]
    vips_array_copy =vips_array.copy()
    for j in features:
        coords = j["geometry"]["coordinates"]
        class_type = j["properties"]["classification"]["names"][0]
        cnt = np.array(coords[0])
        print(len(cnt.shape))
        if len(cnt.shape)==2:
            tiling(cnt,vips_img, vips_array_copy, filename, class_type, orig_w, orig_h)
        else:
            print(filename, cnt.shape)

PD130_Syn1_CG.svs
2

/tmp/ipykernel_1788023/341735292.py:53: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cnt = cnt.astype(np.int)

Crop slide thread Started. 0
---------copying image---------
Crop slide thread Started. 1
---------copying image---------
Crop slide thread Started. 2
---------copying image---------
Crop slide thread Started. 3
---------copying image---------
Crop slide thread Started. 4
---------copying image---------
Crop slide thread Started. 5
---------copying image---------
Crop slide thread Started. 6
---------copying image---------
Crop slide thread Started. 7
---------copying image---------
Crop slide thread Started. 8
---------copying image---------
Crop slide thread Started. 9
---------copying image---------
Thread Stopped  3
Crop slide thread Started. 10
---------copying image---------
Thread Stopped  0
Crop slide thread Started. 11
---------copying image---------
Thread Stopped  5
Crop slide thread Started. 12
---------copying image---------
Thread Stopped  1
Crop slide thread Started. 13
---------copying image---------
Thread Stopped  6
Crop slide thread Started. 14
---------copying image---------
Thread Stopped  4
Crop slide thread Started. 15
---------copying image---------
Thread Stopped  8
Crop slide thread Started. 16
---------copying image---------
Thread Stopped  9
Crop slide thread Started. 17
---------copying image---------
Thread Stopped  7
Crop slide thread Started. 18
---------copying image---------
Thread Stopped  2
Crop slide thread Started. 19
---------copying image---------
Thread Stopped  11
Crop slide thread Started. 20
---------copying image---------
Thread Stopped  10
Crop slide thread Started. 21
---------copying image---------
Thread Stopped  12
Crop slide thread Started. 22
---------copying image---------
Thread Stopped  13
Crop slide thread Started. 23
---------copying image---------
Thread Stopped  15
Crop slide thread Started. 24
---------copying image---------
Thread Stopped  14
Crop slide thread Started. 25
---------copying image---------
Thread Stopped  16
Crop slide thread Started. 26
---------copying image---------
Thread Stopped  19
Crop slide thread Started. 27
---------copying image---------
Thread Stopped  18
Crop slide thread Started. 28
---------copying image---------
Thread Stopped  17
Crop slide thread Started. 29
---------copying image---------
Thread Stopped  20
Crop slide thread Started. 30
---------copying image---------
Thread Stopped  21
Crop slide thread Started. 31
---------copying image---------
Thread Stopped  23
Crop slide thread Started. 32
---------copying image---------
Thread Stopped  22
Crop slide thread Started. 33
---------copying image---------
Thread Stopped  24
Crop slide thread Started. 34
---------copying image---------
Thread Stopped  25
Thread Stopped  26
Thread Stopped  27
Thread Stopped  28
Thread Stopped  29
Thread Stopped  32
Thread Stopped  33
Thread Stopped  30
Thread Stopped  34
Thread Stopped  31
done tiling
2
Crop slide thread Started.Crop slide thread Started. 1
---------copying image---------
 0
---------copying image---------
Crop slide thread Started. 2
---------copying image---------
Crop slide thread Started. 3
---------copying image---------
Crop slide thread Started. 4
---------copying image---------
Crop slide thread Started. 5
---------copying image---------
Crop slide thread Started. 6
---------copying image---------
Crop slide thread Started. 7
---------copying image---------
Crop slide thread Started. 8
---------copying image---------
Crop slide thread Started. 9
---------copying image---------
Thread Stopped  2
Crop slide thread Started. 10
---------copying image---------
Thread Stopped  1
Crop slide thread Started. 11
---------copying image---------
Thread Stopped  0
Crop slide thread Started. 12
---------copying image---------
Thread Stopped  4
Crop slide thread Started. 13
---------copying image---------
Thread Stopped  5
Crop slide thread Started. 14
---------copying image---------
Thread Stopped  8
Crop slide thread Started. 15
---------copying image---------
Thread Stopped  7
Crop slide thread Started. 16
---------copying image---------
Thread Stopped  9
Crop slide thread Started. 17
---------copying image---------
Thread Stopped  3
Crop slide thread Started. 18
---------copying image---------
Thread Stopped  6
Crop slide thread Started. 19
---------copying image---------
Thread Stopped  10
Crop slide thread Started. 20
---------copying image---------
Thread Stopped  11
Crop slide thread Started. 21
---------copying image---------
Thread Stopped  12
Crop slide thread Started. 22
---------copying image---------
Thread Stopped  13
Crop slide thread Started. 23
---------copying image---------
Thread Stopped  14
Crop slide thread Started. 24
---------copying image---------
Thread Stopped  16
Crop slide thread Started. 25
---------copying image---------
Thread Stopped  15
Crop slide thread Started. 26
---------copying image---------
Thread Stopped  17
Crop slide thread Started. 27
---------copying image---------
Thread Stopped  19
Crop slide thread Started. 28
---------copying image---------
Thread Stopped  18
Crop slide thread Started. 29
---------copying image---------
Thread Stopped  22
Crop slide thread Started. 30
---------copying image---------
Thread Stopped  21
Crop slide thread Started. 31
---------copying image---------
Thread Stopped  23
Crop slide thread Started. 32
---------copying image---------
Thread Stopped  20
Crop slide thread Started. 33
---------copying image---------
Thread Stopped  24
Crop slide thread Started. 34
---------copying image---------
Thread Stopped  25
Crop slide thread Started. 35
---------copying image---------
Thread Stopped  27
Crop slide thread Started. 36
---------copying image---------
Thread Stopped  29
Crop slide thread Started. 37
---------copying image---------
Thread Stopped  26
Crop slide thread Started. 38
---------copying image---------
Thread Stopped  28
Crop slide thread Started. 39
---------copying image---------
Thread Stopped  31
Crop slide thread Started. 40
---------copying image---------
Thread Stopped  30
Crop slide thread Started. 41
---------copying image---------
Thread Stopped  32
Crop slide thread Started. 42
---------copying image---------
Thread Stopped  33
Crop slide thread Started. 43
---------copying image---------
Thread Stopped  34
Crop slide thread Started. 44
---------copying image---------
Thread Stopped  35
Crop slide thread Started. 45
---------copying image---------
Thread Stopped  36
Crop slide thread Started. 46
---------copying image---------
Thread Stopped  37
Crop slide thread Started. 47
---------copying image---------
Thread Stopped  38
Crop slide thread Started. 48
---------copying image---------
Thread Stopped  39
Crop slide thread Started. 49
---------copying image---------
Thread Stopped  41
Crop slide thread Started. 50
---------copying image---------
Thread Stopped  40
Crop slide thread Started. 51
---------copying image---------
Thread Stopped  42
Crop slide thread Started. 52
---------copying image---------
Thread Stopped  43
Crop slide thread Started. 53
---------copying image---------
Thread Stopped  44
Crop slide thread Started. 54
---------copying image---------
Thread Stopped  45
Crop slide thread Started. 55
---------copying image---------
Thread Stopped  46
Crop slide thread Started. 56
---------copying image---------
Thread Stopped  47
Crop slide thread Started. 57
---------copying image---------
Thread Stopped  48
Crop slide thread Started. 58
---------copying image---------
Thread Stopped  49
Crop slide thread Started. 59
---------copying image---------
Thread Stopped  50
Crop slide thread Started. 60
---------copying image---------
Thread Stopped  51
Crop slide thread Started. 61
---------copying image---------
Thread Stopped  52
Crop slide thread Started. 62
---------copying image---------
Thread Stopped  53
Crop slide thread Started. 63
---------copying image---------
Thread Stopped  55
Crop slide thread Started. 64
---------copying image---------
Thread Stopped  54
Crop slide thread Started. 65
---------copying image---------
Thread Stopped  56
Crop slide thread Started. 66
---------copying image---------
Thread Stopped  57
Crop slide thread Started. 67
---------copying image---------
Thread Stopped  58
Crop slide thread Started. 68
---------copying image---------
Thread Stopped  59
Crop slide thread Started. 69
---------copying image---------
Thread Stopped  60
Crop slide thread Started. 70
---------copying image---------
Thread Stopped  61
Crop slide thread Started. 71
---------copying image---------
Thread Stopped  64
Crop slide thread Started. 72
---------copying image---------
Thread Stopped  62
Crop slide thread Started. 73
---------copying image---------
Thread Stopped  63
Crop slide thread Started. 74
---------copying image---------
Thread Stopped  65
Crop slide thread Started. 75
---------copying image---------
Thread Stopped  66
Crop slide thread Started. 76
---------copying image---------
Thread Stopped  67
Crop slide thread Started. 77
---------copying image---------
Thread Stopped  68
Crop slide thread Started. 78
---------copying image---------
Thread Stopped  69
Crop slide thread Started. 79
---------copying image---------
Thread Stopped  71
Crop slide thread Started. 80
---------copying image---------
Thread Stopped  70
Crop slide thread Started. 81
---------copying image---------
Thread Stopped  73
Crop slide thread Started. 82
---------copying image---------
Thread Stopped  72
Crop slide thread Started. 83
---------copying image---------
Thread Stopped  74
Crop slide thread Started. 84
---------copying image---------
Thread Stopped  75
Crop slide thread Started. 85
---------copying image---------
Thread Stopped  76
Crop slide thread Started. 86
---------copying image---------
Thread Stopped  77
Crop slide thread Started. 87
---------copying image---------
Thread Stopped  78
Crop slide thread Started. 88
---------copying image---------
Thread Stopped  79
Crop slide thread Started. 89
---------copying image---------
Thread Stopped  81
Crop slide thread Started. 90
---------copying image---------
Thread Stopped  80
Crop slide thread Started. 91
---------copying image---------
Thread Stopped  82
Crop slide thread Started. 92
---------copying image---------
Thread Stopped  83
Crop slide thread Started. 93
---------copying image---------
Thread Stopped  85
Crop slide thread Started. 94
---------copying image---------
Thread Stopped  84
Crop slide thread Started. 95
---------copying image---------
Thread Stopped  86
Crop slide thread Started. 96
---------copying image---------
Thread Stopped  87
Crop slide thread Started. 97
---------copying image---------
Thread Stopped  88
Crop slide thread Started. 98
---------copying image---------
Thread Stopped  89
Crop slide thread Started. 99
---------copying image---------
Thread Stopped  90
Crop slide thread Started. 100
---------copying image---------
Thread Stopped  91
Crop slide thread Started. 101
---------copying image---------
Thread Stopped  92
Crop slide thread Started. 102
---------copying image---------
Thread Stopped  93
Crop slide thread Started. 103
---------copying image---------
Thread Stopped  96
Crop slide thread Started. 104
---------copying image---------
Thread Stopped  97
Crop slide thread Started. 105
---------copying image---------
Thread Stopped  95
Crop slide thread Started. 106
---------copying image---------
Thread Stopped  94
Crop slide thread Started. 107
---------copying image---------
Thread Stopped  98
Crop slide thread Started. 108
---------copying image---------
Thread Stopped  99
Crop slide thread Started. 109
---------copying image---------
Thread Stopped  100
Crop slide thread Started. 110
---------copying image---------
Thread Stopped  101
Crop slide thread Started. 111
---------copying image---------
Thread Stopped  102
Crop slide thread Started. 112
---------copying image---------
Thread Stopped  103
Crop slide thread Started. 113
---------copying image---------
Thread Stopped  104
Crop slide thread Started. 114
---------copying image---------
Thread Stopped  106
Crop slide thread Started. 115
---------copying image---------
Thread Stopped  105
Crop slide thread Started. 116
---------copying image---------
Thread Stopped  107
Crop slide thread Started. 117
---------copying image---------
Thread Stopped  108
Crop slide thread Started. 118
---------copying image---------
Thread Stopped  109
Crop slide thread Started. 119
---------copying image---------
Thread Stopped  110
Crop slide thread Started. 120
---------copying image---------
Thread Stopped  111
Crop slide thread Started. 121
---------copying image---------
Thread Stopped  112
Crop slide thread Started. 122
---------copying image---------
Thread Stopped  113
Crop slide thread Started. 123
---------copying image---------
Thread Stopped  114
Crop slide thread Started. 124
---------copying image---------
Thread Stopped  115
Crop slide thread Started. 125
---------copying image---------
Thread Stopped  116
Crop slide thread Started. 126
---------copying image---------
Thread Stopped  118
Crop slide thread Started. 127
---------copying image---------
Thread Stopped  117
Crop slide thread Started. 128
---------copying image---------
Thread Stopped  119
Crop slide thread Started. 129
---------copying image---------
Thread Stopped  120
Crop slide thread Started. 130
---------copying image---------
Thread Stopped  121
Crop slide thread Started. 131
---------copying image---------
Thread Stopped  122
Crop slide thread Started. 132
---------copying image---------
Thread Stopped  124
Crop slide thread Started. 133
---------copying image---------
Thread Stopped  123
Crop slide thread Started. 134
---------copying image---------
Thread Stopped  125
Crop slide thread Started. 135
---------copying image---------
Thread Stopped  126
Crop slide thread Started. 136
---------copying image---------
Thread Stopped  127
Crop slide thread Started. 137
---------copying image---------
Thread Stopped  128
Crop slide thread Started. 138
---------copying image---------
Thread Stopped  129
Crop slide thread Started. 139
---------copying image---------
Thread Stopped  131
Crop slide thread Started. 140
---------copying image---------
Thread Stopped  130
Crop slide thread Started. 141
---------copying image---------
Thread Stopped  132
Crop slide thread Started. 142
---------copying image---------
Thread Stopped  133
Crop slide thread Started. 143
---------copying image---------
Thread Stopped  134
Crop slide thread Started. 144
---------copying image---------
Thread Stopped  135
Crop slide thread Started. 145
---------copying image---------
Thread Stopped  136
Crop slide thread Started. 146
---------copying image---------
Thread Stopped  139
Crop slide thread Started. 147
---------copying image---------
Thread Stopped  138
Crop slide thread Started. 148
---------copying image---------
Thread Stopped  137
Crop slide thread Started. 149
---------copying image---------
Thread Stopped  140
Crop slide thread Started. 150
---------copying image---------
Thread Stopped  141
Crop slide thread Started. 151
---------copying image---------
Thread Stopped  142
Crop slide thread Started. 152
---------copying image---------
Thread Stopped  143
Crop slide thread Started. 153
---------copying image---------
Thread Stopped  144
Crop slide thread Started. 154
---------copying image---------
Thread Stopped  146
Crop slide thread Started. 155
---------copying image---------
Thread Stopped  145
Crop slide thread Started. 156
---------copying image---------
Thread Stopped  147
Crop slide thread Started. 157
---------copying image---------
Thread Stopped  148
Crop slide thread Started. 158
---------copying image---------
Thread Stopped  149
Crop slide thread Started. 159
---------copying image---------
Thread Stopped  150
Crop slide thread Started. 160
---------copying image---------
Thread Stopped  151
Crop slide thread Started. 161
---------copying image---------
Thread Stopped  153
Crop slide thread Started. 162
---------copying image---------
Thread Stopped  154
Crop slide thread Started. 163
---------copying image---------
Thread Stopped  152
Crop slide thread Started. 164
---------copying image---------
Thread Stopped  155
Crop slide thread Started. 165
---------copying image---------
Thread Stopped  158
Crop slide thread Started. 166
---------copying image---------
Thread Stopped  156
Crop slide thread Started. 167
---------copying image---------
Thread Stopped  157
Crop slide thread Started. 168
---------copying image---------
Thread Stopped  159
Crop slide thread Started. 169
---------copying image---------
Thread Stopped  160
Crop slide thread Started. 170
---------copying image---------
Thread Stopped  161
Thread Stopped  162
Thread Stopped  164
Thread Stopped  163
Thread Stopped  165
Thread Stopped  167
Thread Stopped  166
Thread Stopped  169
Thread Stopped  168
Thread Stopped  170
done tiling
2
Crop slide thread Started. 0
---------copying image---------
Crop slide thread Started. 1
---------copying image---------
Crop slide thread Started. 2
---------copying image---------
Crop slide thread Started. 3
---------copying image---------
Crop slide thread Started. 4
---------copying image---------
Crop slide thread Started. 5
---------copying image---------
Crop slide thread Started. 6
---------copying image---------
Crop slide thread Started. 7
---------copying image---------
Crop slide thread Started. 8
---------copying image---------
Crop slide thread Started. 9
---------copying image---------
Thread Stopped  0
Crop slide thread Started. 10
---------copying image---------
Thread Stopped  2
Crop slide thread Started. 11
---------copying image---------
Thread Stopped  1
Crop slide thread Started. 12
---------copying image---------
Thread Stopped  9
Crop slide thread Started. 13
---------copying image---------
Thread Stopped  4
Crop slide thread Started. 14
---------copying image---------
Thread Stopped  8
Crop slide thread Started. 15
---------copying image---------
Thread Stopped  6
Crop slide thread Started. 16
---------copying image---------
Thread Stopped  5
Crop slide thread Started. 17
---------copying image---------
Thread Stopped  3
Crop slide thread Started. 18
---------copying image---------
Thread Stopped  7
Crop slide thread Started. 19
---------copying image---------
Thread Stopped  10
Crop slide thread Started. 20
---------copying image---------
Thread Stopped  11
Crop slide thread Started. 21
---------copying image---------
Thread Stopped  13
Crop slide thread Started. 22
---------copying image---------
Thread Stopped  12
Crop slide thread Started. 23
---------copying image---------
Thread Stopped  19
Crop slide thread Started. 24
---------copying image---------
Thread Stopped  16
Crop slide thread Started. 25
---------copying image---------
Thread Stopped  15
Crop slide thread Started. 26
---------copying image---------
Thread Stopped  18
Crop slide thread Started. 27
---------copying image---------
Thread Stopped  14
Crop slide thread Started. 28
---------copying image---------
Thread Stopped  17
Crop slide thread Started. 29
---------copying image---------
Thread Stopped  20
Crop slide thread Started. 30
---------copying image---------
Thread Stopped  21
Crop slide thread Started. 31
---------copying image---------
Thread Stopped  22
Crop slide thread Started. 32
---------copying image---------
Thread Stopped  23
Crop slide thread Started. 33
---------copying image---------
Thread Stopped  29
Crop slide thread Started. 34
---------copying image---------
Thread Stopped  25
Crop slide thread Started. 35
---------copying image---------
Thread Stopped  26
Crop slide thread Started. 36
---------copying image---------
Thread Stopped  24
Crop slide thread Started. 37
---------copying image---------
Thread Stopped  27
Crop slide thread Started. 38
---------copying image---------
Thread Stopped  28
Crop slide thread Started. 39
---------copying image---------
Thread Stopped  30
Crop slide thread Started. 40
---------copying image---------
Thread Stopped  31
Crop slide thread Started. 41

In [33]:
annotations_df

,filename,filepath,WM_count,GM_count,bg_count
0,PD130_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
1,PD131_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
2,PD090_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
3,PD079_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
4,PD088_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
5,PD110_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
6,PD001_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
7,PD113_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
8,PD067_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
9,PD133_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
10,PD061_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None
11,PD013_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None

In [11]:
annotations_df =  pd.read_csv("/home/mahirwar/Desktop/Monika/npsad_data/monika/LBD/WM_Annotations.csv")

In [34]:
annotations_df["Aug_WM_count"]=annotations_df["filename"].apply(lambda l:count_annotations_flag(l,"White"))
annotations_df["Aug_GM_count"]=annotations_df["filename"].apply(lambda l:count_annotations_flag(l,"grey"))
annotations_df["Aug_bg_count"]=annotations_df["filename"].apply(lambda l:count_annotations_flag(l,"bg"))

In [35]:
annotations_df

,filename,filepath,WM_count,GM_count,bg_count,Aug_WM_count,Aug_GM_count,Aug_bg_count
0,PD130_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,699,1010,1328
1,PD131_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,204,1247,1571
2,PD090_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,1173,2463,1359
3,PD079_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,1369,1993,1195
4,PD088_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,3133,3886,3044
5,PD110_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,349,3593,1015
6,PD001_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,234,140,340
7,PD113_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,1838,2358,2191
8,PD067_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,1207,1909,1193
9,PD133_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,462,1054,1344
10,PD061_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,1701,1516,3776
11,PD013_Syn1_CG.svs.geojson,/gladstone/finkbeiner/steve/work/data/npsad_da...,None,None,None,617,645,1016

In [36]:
annotations_df.sum()

filename        PD130_Syn1_CG.svs.geojsonPD131_Syn1_CG.svs.geo...
filepath        /gladstone/finkbeiner/steve/work/data/npsad_da...
WM_count                                                        0
GM_count                                                        0
bg_count                                                        0
Aug_WM_count                                                12986
Aug_GM_count                                                21814
Aug_bg_count                                                19372
dtype: object